### ISSUE TITLE
lua doc indicates that rpm.vercmp can compare EVRs

### ISSUE THREAD

**Issue by mlschroe** [rpm-software-management/rpm-web#13]
The `user_doc/lua.md` file contains this:
```
vercmp()   Perform RPM version comparison (rpm >= 4.7.0)   rpm.vercmp("1.2-1", "2.0-1")
```
This suggests that rpm.vercmp can compare complete EVRs, while in reality it can only compare version parts.

(This came up in http://bugzilla.suse.com/show_bug.cgi?id=1164553)

**Comment by pmatilai** [comment]
Nod. There's also a related RFE to add a function that *can* do just that: https://github.com/rpm-software-management/rpm/issues/897

**Comment by pmatilai** [comment]
Oh, this has gotten thoroughly forgotten...

The good news is that it was fixed in rpm [in the meanwhile](https://github.com/rpm-software-management/rpm/pull/1221) so the doc is accurate now :smile:

**Comment by Vogtinator** [comment]
> Oh, this has gotten thoroughly forgotten...
> 
> The good news is that it was fixed in rpm [in the meanwhile](https://github.com/rpm-software-management/rpm/pull/1221) so the doc is accurate now 😄

Arguably the best possible outcome!

Might be useful to document which RPM version this was fixed in?
