### ISSUE TITLE
Boolean dependencies do not have information about new richops

### ISSUE THREAD

**Issue by igor-raits** [rpm-software-management/rpm-web#3]
New rich operators appeared in 4.14 are not mentioned on http://rpm.org/user_doc/boolean_dependencies.html.

Would be nice to get documentation on them

**Comment by pmatilai** [comment]
Would be nice if somebody who has a clue about them wrote it :)

**Comment by igor-raits** [comment]
@mlschroe is known for not writing much documentation, that would be me, @Conan-Kudo or @ffesti ;)

**Comment by pmatilai** [comment]
That's kinda the point I was trying to make :D

**Comment by Conan-Kudo** [comment]
Well, I've got some time, I'll take a crack at it...
