### ISSUE TITLE
Update Release maintenance guide

### ISSUE THREAD

**Issue by dmnks** [rpm-software-management/rpm-web#30]
Document the git-native text format for drafting releases that we successfully used for 4.17.1 and also make some other adjustments and notes about things that aren't obvious in the process.

**Comment by pmatilai** [comment]
FWIW, it'd probably make more sense to move that document into rpm sources instead. I don't quite recall why it's not there in the first place, but whatever the reason(s) were in 2014, various things are different now...

**Comment by ffesti** [comment]
Well, the in-tree doc being a total mess no one looked at might be one reason. Another might be that it wasn't available online in a nice form. To move to GitHub was in 2015 when looking at the date of the first PR.

**Comment by dmnks** [comment]
Whichever we decide for, let's do that as a separate change. I'll post a PR for this one so that the diff is obvious, and then we can potentially move it elsewhere.

**Comment by dmnks** [comment]
This is kinda finished now (the guide is now up-to-date with the cmake process) so let's close.
