### ISSUE TITLE
Link for "Fedora RPM Guide" | Page not found

### ISSUE THREAD

**Issue by Ricky-Tigg** [rpm-software-management/rpm-web#34]
Hello. [Here](https://rpm.org/documentation.html), the page referred in the link for _Fedora RPM Guide_ is [reported](https://docs.fedoraproject.org/en-US/Fedora_Draft_Documentation/0.1/html/RPM_Guide/index.html) not found.

**Comment by dralley** [comment]
Several links are broken including the Python language bindings references on the same page.

**Comment by xsuchy** [comment]
In the meantime - **all** links in `RPM Language Bindings` are broken.

**Comment by dralley** [comment]
Please don't close this one.
