### ISSUE TITLE
Reference manual is oudated

### ISSUE THREAD

**Issue by coiby** [rpm-software-management/rpm-web#46]
For example, https://rpm-software-management.github.io/rpm/manual/queryformat.html misses one dash in the command  `rpm –querytags` and this issue has already been fixed in latest [queryformat.md](https://github.com/rpm-software-management/rpm/blob/master/docs/manual/queryformat.md).

**Comment by pmatilai** [comment]
Indeed, the version there was really quite old. I did some cosmetics formatting fixes to the doc now and that seems have woken the GH pages machinery up. No idea what happened there, I guess it would be some sort of caching/timestamp mixup somewhere.

Thanks for reporting!
