### ISSUE TITLE
rpm-4.20 announce should speak about API changes

### ISSUE THREAD

**Issue by soig** [rpm-software-management/rpm-web#53]
https://rpm.org/wiki/Releases/4.20.0 doesn't list any API changes.
But : 
- the internal OpenPGP parser has been removed so rpm/rpmpgp.h saw a lot of changes
- there's a new rpmdsIsSysuser() function
- there's a new rpmMacroBuf class with the associated API
- …

This should be listed.

**Comment by dmnks** [comment]
Good point, the API section has been forgotten. Thanks, we'll add it.

**Comment by dmnks** [comment]
Moved to the rpm repo to make it easier to track: https://github.com/rpm-software-management/rpm/issues/3273
